# new container based environment
sudo: false

cache:
  pip: true
  directories:
    - datamaps/
    - libmaxminddb/
    - pngquant/

addons:
  apt:
    packages:
      - gfortran
      - libatlas-base-dev
      - libatlas-dev
      - libgmp-dev
      - liblapack-dev
      - libmpfr-dev
      - libspatialindex-dev

language: python
python:
    - "2.6"
    - "2.7"
    - "3.4"
    - "3.5"

notifications:
  email:
    - hschlichting@mozilla.com

script:
    - pip install -U pip
    - travis_wait make build
    - make release_compile
    - make test
    - make docs

# mysql is started automatically
services:
  - redis-server
