# new container based environment
sudo: false

# use a download cache for pip
env:
    - PIP_DOWNLOAD_CACHE=$HOME/.pipcache PIP_WHEEL_DIR=$HOME/.wheelhouse
cache:
  directories:
    - $HOME/.pipcache/
    - $HOME/.wheelhouse/

language: python
python:
    - "2.6"
    - "2.7"

notifications:
  email:
    - hschlichting@mozilla.com

script:
    - make build
    - make wheel
    - make release
    - make test

# mysql is started automatically
services:
  - redis-server

# after_script:
#   - make install_vaurien_deps
#   - make mysql_vaurien &
#   - make redis_vaurien &
#   - VENV_BIN=/home/travis/virtualenv/python${TRAVIS_PYTHON_VERSION}/bin make start_ichnaea
